services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: facilitador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - app_network

  api:
    build: .
    container_name: facilitador_api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=facilitador;Username=postgres;Password=postgres
    depends_on:
      - postgres
    networks:
      - app_network

networks:
  app_network:
    driver: bridge